language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - mkdir proto/generated
  - python -m grpc_tools.protoc -Iproto --python_out=proto/generated --grpc_python_out=proto/generated game_controller.proto
script:
  - pytest